project:
  type: website

website:
  title: "M10 Website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: Shiny Apps
        href: essay-on-shiny-apps.qmd
      - text: Shinylive
        href: essay-on-shinylive.qmd

format:
  html:
    theme: journal
    toc: true
    code-fold: true
    number-sections: true
    page-layout: full
